[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bdge-csv-utils"
version = "0.2526.0"
description = "Support scripts to use schemas with CSV files and Databases"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools.packages.find]
where = ["bdge_csv_utils"]
include = ["csv_schema*", "mongo_utils*"]

[tool.pytest.ini_options]
pythonpath = ["."]
