version: '2'
services:

  notebook:
    image: "jupyter/scipy-notebook"
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/bdge
    user: root
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - neo4j

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_heap_maxSize=3G
      - NEO4J_dbms_import_csv_legacy__quote__escaping=false
    ports:
      - "7474:7474"
      - "7687:7687"

