version: "3"

services:
  pig:
    image: fluddeni/hadoop-pig
    ports:
      - "50070:50070" 
      - "8088:8088" 
      - "10020:10020"
    command: /etc/bootstrap.sh -bash
    stdin_open: true
    tty: true
    volumes:
      - ..:/input
