services:
  notebook:
    image: "quay.io/jupyter/scipy-notebook:latest"
    user: root
    ports:
      - "8888:8888"
    # Ejecuta el contenedor con el ID de usuario y grupo del host
    # para evitar problemas de permisos con los volúmenes.
    environment:
      - GRANT_SUDO=yes
      # Establece un token de Jupyter vacío para evitar pedir contraseña
      - JUPYTER_TOKEN=bdge
    volumes:
      - ..:/home/jovyan/bdge
    # Establece el directorio de trabajo al iniciar el notebook
    working_dir: /home/jovyan/bdge
