services:
  notebook:
    image: "quay.io/jupyter/scipy-notebook:latest"
    ports:
      - "8888:8888"
    # Ejecuta el contenedor con el ID de usuario y grupo del host
    # para evitar problemas de permisos con los volúmenes.
    user: "${DUID}:${DGID}"
    environment:
      - GRANT_SUDO=yes
      # Establece un token de Jupyter para no tener que buscarlo en los logs
      - JUPYTER_TOKEN=bdge
    volumes:
      - ..:/home/jovyan/bdge
    # Establece el directorio de trabajo al iniciar el notebook
    working_dir: /home/jovyan/bdge
