services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
      - "7199:7199"
    command: bash -c 'sed -i -e "s/\(storage_port:\).*/\\1 7070/;s/\(tombstone_failure_threshold:\).*/\\1 100000/;s/\(batch_size_warn_threshold:\).*/\\1 128KiB/;s/\(batch_size_fail_threshold:\).*/\\1 1024KiB/" /etc/cassandra/cassandra.yaml && /usr/local/bin/docker-entrypoint.sh cassandra -f'
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "SELECT now() FROM system.local;"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  notebook:
    image: "quay.io/jupyter/scipy-notebook:latest"
    user: root
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work/bdge
      - /tmp/cassandra:/tmp/cassandra
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=bdge
      - DB_HOSTNAME=cassandra
      - RUNNING_IN_CONTAINER=true
    depends_on:
      cassandra:
        condition: service_healthy
