version: "2"
services:

  mongors1:
    image: mongo
    command: mongod --replSet mongors1 --shardsvr --noauth --port 27017
    restart: on-failure
    ports:
      - 27017

  mongors2:
    image: mongo
    command: mongod --replSet mongors2 --shardsvr --noauth --port 27017
    restart: on-failure
    ports:
      - 27017

  mongocfg1:
    image: mongo
    command: mongod --replSet configrs --configsvr --noauth --port 27017
    restart: on-failure
    ports:
      - 27017

  mongos:
    image: mongo
    depends_on:
      - mongocfg1
      - mongors1
      - mongors2
    command: mongos --configdb configrs/mongocfg1:27017 --port 27017
    restart: on-failure
    ports:
      - "27017:27017"

  notebook:
    image: "jupyter/scipy-notebook"
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/bdge
    user: root
    environment:
      - GRANT_SUDO=yes
    depends_on:
      - mongos

