name: Run HBase Notebooks CI

on:
  push:
    branches: [ '*' ]
    paths:
      - 'hbase/*.ipynb'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'hbase/*.ipynb'

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  setup-modified-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4

      - name: Get all changed files.
        id: changed-notebooks
        uses: tj-actions/changed-files@v46
        with:
          matrix: true
          files: hbase/*.ipynb

      - name: Show all changed files
        run: echo "${{ steps.changed-notebooks.outputs.all_changed_files }}"

    outputs:
      notebooks-any_changed: ${{ steps.changed-notebooks.outputs.any_changed }}
      notebooks-changed: ${{ steps.changed-notebooks.outputs.all_changed_files }}

  build-hbase-notebooks:
    uses: ./.github/workflows/run_notebooks.yml
    needs: setup-modified-files
    if: needs.setup-modified-files.outputs.notebooks-any_changed == 'true'
    with:
      python-versions: '["3.10", "3.12", "3.13"]'
      notebooks: ${{ needs.setup-modified-files.outputs.notebooks-changed }}
