name: Run Notebooks Reusable Workflow

on:
  workflow_call:
    inputs:
      python-versions:
        required: true
        type: string
      notebooks:
        required: true
        type: string
      docker-run-line:
        required: false
        type: string
      additional-requirements:
        required: false
        type: string
      environment:
        required: false
        type: string

jobs:

  build-notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ${{ fromJSON(inputs.python-versions) }}
        notebook: ${{ fromJSON(inputs.notebooks) }}

    steps:
    - name: Checkout the repo.
      uses: actions/checkout@v4

    - name: Setup the running environment from the environment input variable
      run: |
        for l in $(jq -r 'keys[] as $k | "\($k)=\"\(.[$k])\""' <<< "${{ fromJson(inputs.environment) }}"); do
          echo $l >> $GITHUB_ENV
          echo "Found environment variable: $l"
        done

    - name: Setup optional docker container
      run: |
        test -n "${{ inputs.docker-run-line }}" && \
          docker run --rm -d ${{ inputs.docker-run-line }}

    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '${{ matrix.python }}'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
        test -n "${{ inputs.additional-requirements }}"  && \
          pip install ${{ inputs.additional-requirements }}

    - name: Create output directory
      run: mkdir -p ${{RUNNER.temp}}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}

    - name: Run notebook
      run: |
        papermill ${{ matrix.notebook }} ${{matrix.notebook}}.output.ipynb

    - name: Convert notebook to HTML
      run: |
        jupyter nbconvert --to html ${{ matrix.notebook }}.output.ipynb
        cp ${{ matrix.notebook }}* ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}

    - name: Convert notebook mame to artifact name to avoid colisions
      id: gen-output-artifact-name
      run: |
        echo "notebook-no-slash=`echo "${{ matrix.notebook }}" | tr '/. ' '---'`" >> "$GITHUB_OUTPUT"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output-notebooks-${{ steps.gen-output-artifact-name.outputs.notebook-no-slash }}-py-${{ matrix.python }}
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}
