name: Run Notebooks CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  build-sql-notebooks:
    runs-on: ubuntu-latest
    env:
      DB_HOSTNAME: "127.0.0.1"
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

    - name: Checkout the repo.
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - run: |
        python3 -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    # Cambiado intro/sesion0.ipynb?
    - name: intro/sesion0 changed?
      id: changed-file-sesion0
      uses: tj-actions/changed-files@v42
      with:
        files: |
          intro/sesion0.ipynb

    - uses: yaananth/run-notebook@v2
      if: steps.changed-file-sesion0.outputs.any_changed == 'true'
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "intro/sesion0.ipynb"
        isReport: False
        poll: True

    # Cambiado sql/sesion1.ipynb?
    - name: sql/sesion1 changed?
      id: changed-file-sesion1
      uses: tj-actions/changed-files@v42
      with:
        files: |
          sql/sesion1.ipynb

    - uses: yaananth/run-notebook@v2
      if: steps.changed-file-sesion1.outputs.any_changed == 'true'
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "sql/sesion1.ipynb"
        isReport: False
        poll: True

    # Cambiado sql/sesion2.ipynb?
    - name: sql/sesion2 changed?
      id: changed-file-sesion2
      uses: tj-actions/changed-files@v42
      with:
        files: |
          sql/sesion2.ipynb

    - uses: yaananth/run-notebook@v2
      if: steps.changed-file-sesion2.outputs.any_changed == 'true'
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "sql/sesion2.ipynb"
        isReport: False
        poll: True

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output-sql
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}

  build-mongo-notebooks:
    runs-on: ubuntu-latest
    env:
      DB_HOSTNAME: "127.0.0.1"
    services:
      mongo:
        image: mongo:6
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
        options: --health-cmd="echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

    - name: Checkout the repo.
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - run: |
        python3 -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    # Cambiado mongo/sesion3.ipynb?
    - name: mongo/sesion3 changed?
      id: changed-file-sesion3
      uses: tj-actions/changed-files@v42
      with:
        files: |
          mongo/sesion3.ipynb

    - uses: yaananth/run-notebook@v2
      if: steps.changed-file-sesion3.outputs.any_changed == 'true'
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "mongo/sesion3.ipynb"
        isReport: False
        poll: True

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output-mongo
        path: ${{ RUNNER.temp }}/nb-runner
      env:
        RUNNER: ${{ toJson(runner) }}

  build-misc-notebooks:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo.
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - run: |
        python3 -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt

    # Cambiado addendum/sesion0.ipynb?
    - name: intro/sesion0 changed?
      id: changed-file-sesion0
      uses: tj-actions/changed-files@v42
      with:
        files: |
          intro/sesion0.ipynb

    - uses: yaananth/run-notebook@v2
      if: steps.changed-file-sesion0.outputs.any_changed == 'true'
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "intro/sesion0.ipynb"
        isReport: False
        poll: True

