name: Run SQL Notebooks CI

on:
  push:
    branches: [ '*' ]
    paths:
      - 'sql/*.ipynb'
      - 'intro/*.ipynb'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'sql/*.ipynb'
      - 'intro/*.ipynb'

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  setup-modified-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4

      - name: Get all changed files.
        id: changed-notebooks
        uses: tj-actions/changed-files@v45
        with:
          matrix: true
          files: |
            - 'sql/*.ipynb'
            - 'intro/*.ipynb'

      - name: Show all changed files
        run: echo "${{ steps.changed-notebooks.outputs.all_changed_files }}"

    outputs:
        notebooks-any_changed: ${{ steps.changed-notebooks.outputs.any_changed }}
        notebooks-changed: ${{ steps.changed-notebooks.outputs.all_changed_files }}

  build-sql-notebooks:
    uses: ./.github/workflows/run_notebooks.yml
    needs: setup-modified-files
    with:
      docker-run-line: "-p3306:3306 -e MYSQL_ROOT_PASSWORD=root --health-cmd='mysqladmin ping' --health-interval=10s --health-timeout=5s --health-retries=3 mysql:8"
      python-versions: '["3.10", "3.12", "3.13"]'
      notebooks: ${{ fromJSON(needs.setup-modified-files.outputs.notebooks-changed) }}
      additional-requirements: "ipython-sql"
